### ISSUE TITLE
Failed to migration: Mysql2::Error: Specified key was too long

### ISSUE THREAD

**Issue by strviola** [jpmcgrath/shortener#111]
I use Ruby 2.5.3 / Rails 5.2.1.1

```
$ rails g shortener
$ rails db:migrate
== 20190206063934 CreateShortenedUrlsTable: migrating =========================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:shortened_urls, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.1877s
-- add_index(:shortened_urls, :unique_key, {:unique=>true})
   -> 0.1547s
-- add_index(:shortened_urls, :url, {:length=>2083})
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Specified key was too long; max key length is 3072 bytes: CREATE  INDEX `index_shortened_urls_on_url`  ON `shortened_urls` (`url`(2083)) 
/Users/******/repositories/******/db/migrate/20190206063934_create_shortened_urls_table.rb:29:in `change'
bin/rails:4:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 3072 bytes: CREATE  INDEX `index_shortened_urls_on_url`  ON `shortened_urls` (`url`(2083)) 
/Users/******/repositories/******/db/migrate/20190206063934_create_shortened_urls_table.rb:29:in `change'
bin/rails:4:in `<main>'

Caused by:
Mysql2::Error: Specified key was too long; max key length is 3072 bytes
/Users/******/repositories/******/db/migrate/20190206063934_create_shortened_urls_table.rb:29:in `change'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by craigmcnamara** [comment]
Without knowing your DB config, I can't really help you with that other than to say, maybe try a smaller limit on the index that fails to add.

Shortener supports many DBs through ActiveRecord, so I'd consider the out of the box migration a suggestion instead of hard and fast config rules. Because of this I'm closing the ticket.
