### ISSUE TITLE
Undefined method except! ActionController::Parameters

### ISSUE THREAD

**Issue by abhinaykumar** [jpmcgrath/shortener#155]
Most probably this line causing the error: https://github.com/jpmcgrath/shortener/blob/630be48c5236c18aab9748af8d768b81378bf945/app/models/shortener/shortened_url.rb#L102

Rails has drop the support for this method. Here is the link to related issue: https://github.com/rails/rails/issues/33110

Stack trace:
```
[shortener (0.5.5) app/controllers/shortener/shortened_urls_controller.rb:21:in `show'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/abstract_controller/base.rb:228:in `process_action'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_controller/metal/rendering.rb:30:in `process_action'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/abstract_controller/callbacks.rb:42:in `block in process_action'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/callbacks.rb:117:in `block in run_callbacks'](http://localhost:3000/live-session/V2HHet#)
[actiontext (6.1.7) lib/action_text/rendering.rb:20:in `with_renderer'](http://localhost:3000/live-session/V2HHet#)
[actiontext (6.1.7) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/callbacks.rb:126:in `instance_exec'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/callbacks.rb:126:in `block in run_callbacks'](http://localhost:3000/live-session/V2HHet#)
[react-rails (2.6.2) lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/callbacks.rb:126:in `block in run_callbacks'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/callbacks.rb:137:in `run_callbacks'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/abstract_controller/callbacks.rb:41:in `process_action'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_controller/metal/rescue.rb:22:in `process_action'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/notifications.rb:203:in `block in instrument'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/notifications/instrumenter.rb:24:in `instrument'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/notifications.rb:203:in `instrument'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:33:in `process_action'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'](http://localhost:3000/live-session/V2HHet#)
[activerecord (6.1.7) lib/active_record/railties/controller_runtime.rb:27:in `process_action'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/abstract_controller/base.rb:165:in `process'](http://localhost:3000/live-session/V2HHet#)
[actionview (6.1.7) lib/action_view/rendering.rb:39:in `process'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_controller/metal.rb:190:in `dispatch'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_controller/metal.rb:254:in `dispatch'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:33:in `serve'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/journey/router.rb:50:in `block in serve'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/journey/router.rb:32:in `each'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/journey/router.rb:32:in `serve'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:842:in `call'](http://localhost:3000/live-session/V2HHet#)
[bullet (6.1.5) lib/bullet/rack.rb:15:in `call'](http://localhost:3000/live-session/V2HHet#)
[scout_apm (2.6.10) lib/scout_apm/instant/middleware.rb:53:in `call'](http://localhost:3000/live-session/V2HHet#)
[scout_apm (2.6.10) lib/scout_apm/middleware.rb:20:in `call'](http://localhost:3000/live-session/V2HHet#)
[warden (1.2.9) lib/warden/manager.rb:36:in `block in call'](http://localhost:3000/live-session/V2HHet#)
[warden (1.2.9) lib/warden/manager.rb:34:in `catch'](http://localhost:3000/live-session/V2HHet#)
[warden (1.2.9) lib/warden/manager.rb:34:in `call'](http://localhost:3000/live-session/V2HHet#)
[rack (2.2.4) lib/rack/static.rb:161:in `call'](http://localhost:3000/live-session/V2HHet#)
[rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'](http://localhost:3000/live-session/V2HHet#)
[rack (2.2.4) lib/rack/etag.rb:27:in `call'](http://localhost:3000/live-session/V2HHet#)
[rack (2.2.4) lib/rack/conditional_get.rb:27:in `call'](http://localhost:3000/live-session/V2HHet#)
[rack (2.2.4) lib/rack/head.rb:12:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/http/permissions_policy.rb:22:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/http/content_security_policy.rb:19:in `call'](http://localhost:3000/live-session/V2HHet#)
[rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'](http://localhost:3000/live-session/V2HHet#)
[rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/middleware/cookies.rb:689:in `call'](http://localhost:3000/live-session/V2HHet#)
[activerecord (6.1.7) lib/active_record/migration.rb:601:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/callbacks.rb:98:in `run_callbacks'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'](http://localhost:3000/live-session/V2HHet#)
[rollbar (3.3.1) lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'](http://localhost:3000/live-session/V2HHet#)
[rollbar (3.3.1) lib/rollbar.rb:145:in `scoped'](http://localhost:3000/live-session/V2HHet#)
[rollbar (3.3.1) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'](http://localhost:3000/live-session/V2HHet#)
[rollbar (3.3.1) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'](http://localhost:3000/live-session/V2HHet#)
[web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'](http://localhost:3000/live-session/V2HHet#)
[web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'](http://localhost:3000/live-session/V2HHet#)
[web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'](http://localhost:3000/live-session/V2HHet#)
[web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'](http://localhost:3000/live-session/V2HHet#)
[railties (6.1.7) lib/rails/rack/logger.rb:37:in `call_app'](http://localhost:3000/live-session/V2HHet#)
[railties (6.1.7) lib/rails/rack/logger.rb:26:in `block in call'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/tagged_logging.rb:99:in `block in tagged'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/tagged_logging.rb:37:in `tagged'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/tagged_logging.rb:99:in `tagged'](http://localhost:3000/live-session/V2HHet#)
[railties (6.1.7) lib/rails/rack/logger.rb:26:in `call'](http://localhost:3000/live-session/V2HHet#)
[sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/middleware/request_id.rb:26:in `call'](http://localhost:3000/live-session/V2HHet#)
[rack (2.2.4) lib/rack/method_override.rb:24:in `call'](http://localhost:3000/live-session/V2HHet#)
[rack (2.2.4) lib/rack/runtime.rb:22:in `call'](http://localhost:3000/live-session/V2HHet#)
[activesupport (6.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/middleware/static.rb:24:in `call'](http://localhost:3000/live-session/V2HHet#)
[rack (2.2.4) lib/rack/sendfile.rb:110:in `call'](http://localhost:3000/live-session/V2HHet#)
[actionpack (6.1.7) lib/action_dispatch/middleware/host_authorization.rb:148:in `call'](http://localhost:3000/live-session/V2HHet#)
[rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'](http://localhost:3000/live-session/V2HHet#)
[webpacker (5.4.3) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'](http://localhost:3000/live-session/V2HHet#)
[rack-proxy (0.7.4) lib/rack/proxy.rb:78:in `call'](http://localhost:3000/live-session/V2HHet#)
[webpacker (5.4.3) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'](http://localhost:3000/live-session/V2HHet#)
[rack-proxy (0.7.4) lib/rack/proxy.rb:78:in `call'](http://localhost:3000/live-session/V2HHet#)
[railties (6.1.7) lib/rails/engine.rb:539:in `call'](http://localhost:3000/live-session/V2HHet#)
[puma (4.3.12) lib/puma/configuration.rb:228:in `call'](http://localhost:3000/live-session/V2HHet#)
[puma (4.3.12) lib/puma/server.rb:727:in `handle_request'](http://localhost:3000/live-session/V2HHet#)
[puma (4.3.12) lib/puma/server.rb:476:in `process_client'](http://localhost:3000/live-session/V2HHet#)
[puma (4.3.12) lib/puma/server.rb:332:in `block in run'](http://localhost:3000/live-session/V2HHet#)
[puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'](http://localhost:3000/live-session/V2HHet#)
```

**Comment by fschwahn** [comment]
You are using a very outdated version of shortener (0.5.5, released in 2015). That version seems to be incompatible with rails 6.1 - you should upgrade to the latest version. 

Please re-open if the issue persists after upgrading.
